[project]
name = "liine-take-home"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.1.0",
    "fastapi>=0.115.12",
    "pandas>=2.2.3",
    "uvicorn>=0.34.2",
]
